# Generated by Django 3.2.9 on 2021-11-26 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20211125_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
    ]
